### ISSUE TITLE
Destroy SheetMusicJSON repository!

### ISSUE THREAD

**Issue by klesun** [klesun/shmidusic#101]
Just create new class, that would override JSONObject::write() method for your beloved indents.

Oh, and yeah, bump issue #90

**Comment by ArturKlesun** [comment]
Cuz yu-no, my fork becomes outdated as time goes

**Comment by klesun** [comment]
i'm afraid i should refuse. original JSONObject uses HashMap to store object keys, but i'd like keys to preserve order, cuz we have important fields, that should be at the start and we have not important/optional fields - when the latter are somewhere at the end, it increases readability.
