### ISSUE TITLE
Highlight sounding notas 'till they finish sounding

### ISSUE THREAD

**Issue by klesun** [klesun/shmidusic#51]
https://noteworthycomposer.com/

As you may see, they keep pressed Nota-s highlighted even when Accord finished. We could do something same with bg highlighting of pressed Nota-s.

Try it, maybe we could steal more features or just think something about compatibility with similar programs like exporting midi-huidi.

midiana is better nevertheless, cuz midiana is open source =P

**Comment by ArturKlesun** [comment]
Checked. Heavy and not understandable.

**Comment by ArturKlesun** [comment]
why?

**Comment by klesun** [comment]
nah
