### ISSUE TITLE
Select multiple accords and peform an operation on every of them

### ISSUE THREAD

**Issue by klesun** [klesun/shmidusic#52]
I need to highen some part of music one octave - make this possible!
// upd.: i already did the thing manually =D

**Comment by ArturKlesun** [comment]
Please, also do same thing for Paragraph-z

**Comment by klesun** [comment]
In particular, i miss copy/paste very much when transcribing stuff

**Comment by klesun** [comment]
aee8fa3f9da1fadf1331babe96f55ad80bac4d06
